### ISSUE TITLE
Boa

### ISSUE THREAD

**Issue by IB1tooSiM** [Goodwy/Keyboard#3]
#### Environment information
- FlorisBoard [0.2.8-beta04](https://github.com/goodwy/keyboard/releases/v0.2.8-beta04) (28)
- Device: Motorola Moto g power 5G - 2024 (cancunn_g_sys)
- Android: 14 (cn=UPSIDE_DOWN_CAKE sdk=34)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-08-28T23:57:05.163722Z
Manufacturer        : motorola
Model               : moto g power 5G - 2024
Product             : cancunn_g_sys
Android             : 14 (cn=UPSIDE_DOWN_CAKE sdk=34) [U1UDS34.16-62-5]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.03 GiB (54.13% used, 7.44 GiB max)
Font scale          : 1.15
Locales             : en-US-u-fw-tue-mu-fahrenhe

======= APP INFO =======
Package             : com.goodwy.keyboard
Name                : Inkwell
Version             : 0.2.8-beta04 (28)
Build type          : release
Build commit hash   : 76ca394aaa19b96f4fd4baf8cae6b5fea33798c3
Java heap memory    : 12.70 MiB (4.96% used, 256.00 MiB max)
Native heap memory  : 12.68 MiB (91.17% used, 13.91 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : false
Glide enabled               : false
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1724889419525.stacktrace</summary>

```
com.google.android.gms.common.api.ApiException: Success! The app crashed purposely to display this beautiful screen we all love :)
	at com.goodwy.keyboard.app.devtools.ComposableSingletons$DevtoolsScreenKt$lambda-3$1$2$1$12.invoke(SourceFile:5)
	at androidx.compose.runtime.Recomposer$effectJob$1$1.invoke(SourceFile:1396)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(SourceFile:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.JobKt.resume(SourceFile:79)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:105)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SourceFile:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SourceFile:31)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Unknown Source:2)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Unknown Source:4)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:157)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.platform.WeakCache.dispatchChanges(SourceFile:36)
	at com.google.android.gms.tasks.zzw.process-BIzXfog(SourceFile:138)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:81)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:214)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3126)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3126)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3126)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3126)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:511)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4505)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:469)
	at android.view.View.dispatchPointerEvent(View.java:15967)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7331)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7125)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6537)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6594)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6560)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6725)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6568)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6782)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6541)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6594)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6560)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6568)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6541)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9685)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9601)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9562)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9832)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:274)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:342)
	at android.os.Looper.loopOnce(Looper.java:183)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8407)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@f94f5bb, androidx.compose.runtime.BroadcastFrameClock@eedcad8, StandaloneCoroutine{Cancelling}@a1d5e31, AndroidUiDispatcher@c1a3916]

```
</details>

**Comment by Goodwy** [comment]
You have clicked the ‘Test crash report screen’ button. This button is specially designed to create an error.
