### ISSUE TITLE
https://github.com/goodwy/keyboard/releases/v0.2.8-beta04

### ISSUE THREAD

**Issue by w1s3one805** [Goodwy/Keyboard#6]
- - #### Environment information
- FlorisBoard [0.2.8-beta04](https://github.com/goodwy/keyboard/releases/v0.2.8-beta04) (28)
- Device: Motorola Moto g stylus 5G - 2023 (genevn_g)
- Android: 14 (cn=UPSIDE_DOWN_CAKE sdk=34)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-11-15T13:02:50.218346Z
Manufacturer        : motorola
Model               : moto g stylus 5G - 2023
Product             : genevn_g
Android             : 14 (cn=UPSIDE_DOWN_CAKE sdk=34) [U1TGNS34.42-86-3-6]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 3.88 GiB (72.20% used, 5.37 GiB max)
Font scale          : 1.0
Locales             : en-US,en-XA,ar-XB

======= APP INFO =======
Package             : com.goodwy.keyboard
Name                : Inkwell
Version             : 0.2.8-beta04 (28)
Build type          : release
Build commit hash   : 76ca394aaa19b96f4fd4baf8cae6b5fea33798c3
Java heap memory    : 37.35 MiB (14.59% used, 256.00 MiB max)
Native heap memory  : 14.89 MiB (95.46% used, 15.60 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : false
Glide enabled               : false
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1731675766367.stacktrace</summary>

```
java.lang.NullPointerException
	at com.goodwy.keyboard.ime.keyboard.ComputingEvaluatorKt.computeImageVector(SourceFile:98)
	at com.goodwy.keyboard.ime.smartbar.quickaction.QuickActionButtonKt.QuickActionButton(SourceFile:100)
	at com.goodwy.keyboard.ime.smartbar.quickaction.QuickActionsRowKt$QuickActionsRow$1$1.invoke(SourceFile:393)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:13)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:24)
	at androidx.compose.material3.ButtonKt$Button$3$1.invoke(SourceFile:191)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:18)
	at androidx.compose.material3.ButtonKt$Button$3$1.invoke(SourceFile:102)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:18)
	at androidx.compose.runtime.Updater.invokeComposable(SourceFile:15)
	at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:122)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(SourceFile:11)
	at androidx.compose.runtime.CompositionImpl.composeContent(SourceFile:35)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(SourceFile:45)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(SourceFile:5)
	at androidx.compose.runtime.CompositionImpl.composeInitial(SourceFile:9)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SourceFile:22)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SourceFile:119)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SourceFile:171)
	at androidx.compose.material3.ButtonKt$Button$3$1.invoke(SourceFile:189)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SourceFile:78)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.SizeNode.measure-3p2s80s(SourceFile:117)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.animation.AnimatedEnterExitMeasurePolicy.measure-3p2s80s(SourceFile:42)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.animation.EnterExitTransitionModifierNode.measure-3p2s80s(SourceFile:184)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(SourceFile:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.material3.TabKt$Tab$2.invoke(SourceFile:3575)
	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:8)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.foundation.layout.RowColumnMeasurementHelper.measureWithoutPlacing-_EkL_-Y(SourceFile:116)
	at androidx.compose.foundation.layout.RowColumnMeasurePolicy.measure-3p2s80s(SourceFile:32)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.animation.AnimatedEnterExitMeasurePolicy.measure-3p2s80s(SourceFile:42)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.animation.EnterExitTransitionModifierNode.measure-3p2s80s(SourceFile:184)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(SourceFile:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.material3.TabKt$Tab$2.invoke(SourceFile:3575)
	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:8)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.foundation.layout.RowColumnMeasurementHelper.measureWithoutPlacing-_EkL_-Y(SourceFile:116)
	at androidx.compose.foundation.layout.RowColumnMeasurePolicy.measure-3p2s80s(SourceFile:32)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(SourceFile:33)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.WrapContentNode.measure-3p2s80s(SourceFile:57)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(SourceFile:83)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.WrapContentNode.measure-3p2s80s(SourceFile:57)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.foundation.layout.RowColumnMeasurementHelper.measureWithoutPlacing-_EkL_-Y(SourceFile:405)
	at androidx.compose.foundation.layout.RowColumnMeasurePolicy.measure-3p2s80s(SourceFile:32)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(SourceFile:33)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.WrapContentNode.measure-3p2s80s(SourceFile:57)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(SourceFile:83)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(SourceFile:115)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.WrapContentNode.measure-3p2s80s(SourceFile:57)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.foundation.layout.RowColumnMeasurementHelper.measureWithoutPlacing-_EkL_-Y(SourceFile:116)
	at androidx.compose.foundation.layout.RowColumnMeasurePolicy.measure-3p2s80s(SourceFile:32)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(SourceFile:96)
	at androidx.compose.ui.layout.RootMeasurePolicy.measure-3p2s80s(SourceFile:39)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at com.goodwy.keyboard.ime.popup.PopupSet$1.invoke(SourceFile:764)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(SourceFile:18)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(Unknown Source:17)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureOnly(SourceFile:63)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(SourceFile:83)
	at android.view.View.measure(View.java:27238)
	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(Unknown Source:63)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:27238)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7037)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27238)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7037)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27238)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7037)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27238)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7037)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27238)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7037)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:771)
	at android.view.View.measure(View.java:27238)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3013)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3379)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2704)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9793)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:1000)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8448)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

```
</details>

**Comment by Goodwy** [comment]
Thanks, will be fixed in the next version.
